name: Check the source code

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.1.0'

    - name: Install dependencies
      run: npm install

    - name: Run linter
      run: npm run lint

  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21.1.0'

    - name: Install dependencies
      run: npm install

    - name: Check version-related files
      run: npm run version-check
